changelog:
  categories:
    - title: New Features
      labels:
        - '*'
      exclude:
        labels:
          - bug
          - dependencies
    - title: Bug Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
