complexity:
  TooManyFunctions:
    active: false

formatting:
  ArgumentListWrapping:
    maxLineLength: 140
  FunctionReturnTypeSpacing:
    maxLineLength: 140
  FunctionSignature:
    maxLineLength: 140
  MaximumLineLength:
    maxLineLength: 140
  NoUnusedImports:
    # Issues with context parameters
    active: false
  ParameterListWrapping:
    maxLineLength: 140
  ParameterWrapping:
    maxLineLength: 140
  PropertyWrapping:
    maxLineLength: 140
  SpacingAroundColon:
    # Issues with context parameters
    active: false
  Wrapping:
    # Issues with context parameters
    active: false
    maxLineLength: 140

style:
  MaxLineLength:
    active: false
