name: Deploy

on:
  push:
    tags: [ "*" ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  packages:
    name: Packages
    runs-on: macos-26

    permissions:
      contents: write # Required for creating release
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Cache Kotlin/Native toolchains
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Install Vulkan SDK
        uses: technoir-lab/install-vulkan-sdk@v1.2.3
        with:
          version: 1.4.328.0
          cache: true

      - name: Set environment variables
        run: |
          echo "C_INCLUDE_PATH=${{ env.VULKAN_SDK }}/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=${{ env.VULKAN_SDK }}/lib" >> $GITHUB_ENV

      - name: Publish to GitHub Packages
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishAllPublicationsToGithubRepository \
          --scan \
          -Pproject.version=${{ github.ref_name }} \
          -Ppublish.github.username=${{ secrets.GPR_DEPLOY_USER }} \
          -Ppublish.github.password=${{ secrets.GPR_DEPLOY_TOKEN }}

      - name: Publish to Maven Central
        env:
          CENTRAL_PORTAL_USER: ${{ secrets.CENTRAL_PORTAL_USER }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishAggregationToCentralPortal \
          --scan \
          -Pproject.version=${{ github.ref_name }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true

  documentation:
    name: Documentation
    runs-on: macos-26

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Cache Kotlin/Native toolchains
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Install Vulkan SDK
        uses: technoir-lab/install-vulkan-sdk@v1.2.3
        with:
          version: 1.4.328.0
          cache: true

      - name: Set environment variables
        run: |
          echo "C_INCLUDE_PATH=${{ env.VULKAN_SDK }}/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=${{ env.VULKAN_SDK }}/lib" >> $GITHUB_ENV

      - name: Generate documentation
        run: |
          ./gradlew :vulkan-kotlin:dokkaGenerate \
          --scan \
          -Pproject.version=${{ github.ref_name }}

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v4
        with:
          path: vulkan-kotlin/build/dokka/html

      - name: Deploy documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
